# Generated by Django 4.0.4 on 2022-04-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
                ('invoiceNumber', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('reportedTo', models.CharField(max_length=100)),
                ('solved', models.CharField(max_length=50)),
            ],
        ),
    ]
